### ISSUE TITLE
Loadout Item Selection does not hide screen behind it completly

### ISSUE THREAD

**Issue by Wonkglorg** [Hypnootize/hexhud#20]
When clicking on any item to change it the slots do not get properly hidden duo to my screen size. 

This was not the case in the old one, I understand it is not a supported screen size but wanted to bring attention to it regardless, if widescreen does get support at some point or at least partial fixes. 

Technical Details:
Screen size: 3440 x 1440
Ratio: 21:9

![Screenshot_2](https://github.com/user-attachments/assets/e36000e5-9ad1-4f04-87d4-210b290951e9)

**Comment by Hypnootize** [comment]
Yeah that's expected with any aspect ratio other than 16:9 (and 16:10 in part) sadly. I probably won't be trying to fix or adapt the HUD to widescreen anytime soon as I don't even have a proper way to test.

The solution to it it's super easy tho, open `resource/ui/itemselectionpanel.res` and change the color for the `"bgcolor_override"` [HERE](https://github.com/Hypnootize/hexhud/blob/master/resource/ui/itemselectionpanel.res#L21) to `Background_Main` instead of `Blank`

This might end up cutting off part of the hexagons on the sides but it's probably a fair trade to get it working properly.

**Comment by Wonkglorg** [comment]
Thanks for the quick reply no worries about fixing it I can manage.

Another question, was there a reason the old tool menu has been discontinued or has it moved somewhere I didn't find yet?

It was very useful especially the fix invis players and audio reloads

**Comment by Hypnootize** [comment]
Well... I've forgot about them ahah, now that you mention it I should probably re-add them among the other buttons in the bottom left

**Comment by Hypnootize** [comment]
They are back now, ty for mentioning it!

**Comment by Wonkglorg** [comment]
Thank you! Great update btw, really enjoy the new look,
