### ISSUE TITLE
Oddly blurry and pixelated class images in match status (also applies to casual levels in the scoreboard)

### ISSUE THREAD

**Issue by Duptier** [Hypnootize/hexhud#5]
![image](https://user-images.githubusercontent.com/82429716/124052532-ef83b080-da61-11eb-80d9-788699762820.png)
Second issue I've noticed, Again, not sure if this is a "me" issue, but I'm still going to point it out for you.

Though, this _could_ be due to me using Arch Linux - again, not sure - but it is still prevalent.

**Comment by Hypnootize** [comment]
The main issue here is how I scaled down the icon in order to make it fit in this match status design, which normally I would have fixed by using custom icons but the game doesn't load any custom class portrait in pure servers sadly so there isn't much I can do about this, or at least without touching the match status design itself and I'm not willing to.
